kafka_poc_produce:
    path:     /kafka/produce
    defaults: { _controller: KafkaPocBundle:Default:produce }

kafka_poc_consume:
    path:     /kafka/consume
    defaults: { _controller: KafkaPocBundle:Default:consume }
