kafka_poc_produce:
    path:     /kafka/produce
    defaults: { _controller: KafkaPocBundle:Default:produce }

kafka_poc_consume:
    path:     /kafka/consume
    defaults: { _controller: KafkaPocBundle:Default:consume }

kafka_poc_movie_dl:
    path:     /kafka/dl
    defaults: { _controller: KafkaPocBundle:Default:dl }  

kafka_poc_movie_full:
    path:     /kafka/full
    defaults: { _controller: KafkaPocBundle:Default:fullMovie }

kafka_poc_movie_partial:
    path:     /kafka/partial
    defaults: { _controller: KafkaPocBundle:Default:partialMovie }