rabbit_mq_poc_workqueue_produce:
    path:     /workqueue/produce
    defaults: { _controller: RabbitMqPocBundle:Default:workQueue }

rabbit_mq_poc_pubsub_produce:
    path:     /pubsub/produce
    defaults: { _controller: RabbitMqPocBundle:Default:pubSub }
