---

workspace: /var/www/rabbit_kafka

timezone: Europe/Paris

sites:
  - { name: 'rabbit-kafka', docroot: '/var/www/rabbit_kafka', server_name: 'rabbit-kafka.poc', template: 'vhost.symfony.j2' }


rabbitmq:
  users:
    - { name: 'admin' }

php_versions: ['7.0'] # main php version will be 7.0 because it's the first value

# etc_hosts_lines:
#   - { ip: '192.168.100.12', hostname: 'other-vm-containing-redis-and-elasticsearch' }
#   - { ip: '192.168.100.14', hostname: 'microservice-hosted-elsewhere.dev' }

logstash_config: >
  input {
    redis {
      data_type => list
      host => other-vm-containing-redis-and-elasticsearch
      key => a_random_key
    }
  }
  output {
    elasticsearch {
      index => my_index
      document_type => my_type
      hosts => ["other-vm-containing-redis-and-elasticsearch:9200"]
    }
  }
